### ISSUE TITLE
setlist can't be reversed

### ISSUE THREAD

**Issue by laurent-laporte-pro** [mlenzen/collections-extended#125]
Using collections_extended v1.0.3:

A `setlist` can't be reversed with `reverse` method:

```python
from collections_extended import setlist
l = setlist("abc")
l.reverse()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../_collections_abc.py", line 985, in reverse
    self[i], self[n-i-1] = self[n-i-1], self[i]
  File ".../collections_extended/setlists.py", line 330, in __setitem__
    raise ValueError
ValueError
```

This is because the original implementation (`_collections_abc.MutableSequence.reverse`) uses the "swap" technique.

**Comment by laurent-laporte-pro** [comment]
Sugested bug fix, implement `reverse`:

```python
    def reverse(self):
        self._list.reverse()
```

**Comment by mlenzen** [comment]
Thanks @laurent-laporte-pro I've made the fix and it will be in the next release.
